language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database parkitectnexus_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --force

script:
  - vendor/bin/phpunit